config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [ :index, :show, :new, :create ] do
  resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie 
  belongs_to :list
  
  validates :movie, :list, presence: true
  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmark_path(@bookmark)
    else
    render :new
    end
  end

  def destroy
    @bookmark.delete(:bookmark)
  end

private

def bookmark_params
  params.require(:bookmark).permit(:comment)
end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.name %></li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.input :comment %>
  <%= f.submit "Add Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/show.html.erb
<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmark_path %> |
<%= link_to 'Leave a comment', new_bookmark_comment_path(@bookmark) %>

<ul class="list-group">
  <% @bookmark.reviews.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.content %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :comment %>
  <%= f.submit "Add List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
  <% @list.movies.each do |movie| %>
  <div class="movie-card">
    <h3><%= movie.title %></h3>
    <p><%= movie.overview %></p>
  </div>
  <% end %>

<%= link_to "Back", lists_path %>